<?php
                /*ABOUT 1.0.0*/                
                'id_about_1_0_0' => array(
                    'key' => 'id_about_1_0_0',
                    'name' => 'about_1_0_0',
                    'label' => 'About 1.0.0',
                    'display' => 'block',
                    'sub_fields' => array(
                        /*Bắt đầu field*/
                        array(
                            /* Tab tiêu đề*/
                            'key' => 'id_about_1_0_tab1',
                            'label' => 'Tiêu Đề',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'id_about_1_0_tab1_sub1',
                            'label' => 'Tiêu đề',
                            'name' => 'about_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            /* Tab About*/
                            'key' => 'id_about_1_0_0_tab2',
                            'label' => 'Nội Dung',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'id_about_1_0_0_tab2_sub1',
                            'label' => 'Mô tả',
                            'name' => 'about_des',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
                        ),
                        array(
                            'key' => 'id_about_1_0_0_tab2_sub2',
                            'label' => 'Link liên kết',
                            'name' => 'about_more',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '#',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            /* Tab Clip*/
                            'key' => 'id_about_1_0_0_tab3',
                            'label' => 'Video Clip',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'id_about_1_0_0_tab3_sub1',
                            'label' => 'Link Youtube',
                            'name' => 'about_ytblink',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        
                        
                        /*End field*/
                    ),
                    'min' => '',
                    'max' => '',
                ),
                /*END ABOUT 1.0.0*/
?>