<?php 
	array(
		'key' => 'field_5d7747cfedfbb',
		'label' => 'Menu',
		'name' => 'menu',
		'type' => 'flexible_content',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layouts' => array(
			'layout_5d77479867072' => array(
				'key' => 'layout_5d77479867072',
				'name' => 'menu_don',
				'label' => 'Menu đơn',
				'display' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5d77480eedfbc',
						'label' => 'Tên Menu',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d774822edfbd',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
				'min' => '',
				'max' => '',
			),
			'layout_5d774841edfbe' => array(
				'key' => 'layout_5d774841edfbe',
				'name' => 'menu_da_cap',
				'label' => 'Menu đa cấp',
				'display' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5d774841edfbf',
						'label' => 'Tên Menu',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d774841edfc0',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d774899edfc1',
						'label' => 'Số cột sub',
						'name' => 'num',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => '1 cột',
							2 => '2 cột',
							3 => '3 cột',
							4 => '4 cột',
						),
						'default_value' => array(
							0 => 1,
							1 => 2,
							2 => 3,
							3 => 4,
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5d774a10d0e8c',
						'label' => 'Cột 1',
						'name' => 'col1',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5d774a63d0e90',
						'label' => 'Sub',
						'name' => 'sub_col2',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '2',
								),
							),
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '3',
								),
							),
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '4',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5d774a32d0e8d',
						'label' => 'Cột 2',
						'name' => 'col2',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '2',
								),
							),
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '3',
								),
							),
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '4',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5d774a73d0e91',
						'label' => 'Sub',
						'name' => 'sub_col3',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '3',
								),
							),
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '4',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5d774a3dd0e8e',
						'label' => 'Cột 3',
						'name' => 'col3',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '3',
								),
							),
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '4',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5d774aa9d0e92',
						'label' => 'Sub',
						'name' => 'sub_col4',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '4',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5d774a51d0e8f',
						'label' => 'Cột 4',
						'name' => 'col4',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5d774899edfc1',
									'operator' => '==',
									'value' => '4',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
				),
				'min' => '',
				'max' => '',
			),
		),
		'button_label' => 'Add Row',
		'min' => '',
		'max' => '',
	),
?>